### ISSUE TITLE
Add CDPP formula

### ISSUE THREAD

**Issue by mirca** [KeplerGO/pyke#146]

**Comment by barentsen** [comment]
It may already be implemented in the old PyKE, here:

https://github.com/KeplerGO/pyke/blob/09220937fbf6d683499dfcfb49a69bccac6d1f8c/pyke/kepstddev.py#L18

However I think we should:
* check that the formula matches that of the Christiaensen et al paper;
* turn it into a simple lightweight function (e.g. in `utils.py`);
* make sure the function has a reference to the literature where the formula is explained;
* add a `Lightcurve.cddp()` method (?) which wraps the function (I think having it as a separate function is useful).

**Comment by dacmess** [comment]
kepstddev is not really CDPP. Real "CDPP" is computed in the wavelet domain on the whitened time series, hence the reason it's not widely reproduced. A closer proxy to CDPP might be the Savitsky-Golay filter approach used by Gilliland et al. 2015, AJ 150 (see Section 4.1, or ask JVC or me). 

I seem to recall that there was some error -or at least non-standard computation- in kepstddev, but I'll have to look back at my notes for more details.

**Comment by barentsen** [comment]
Excellent point!  However I see CDPP as defined by Christiansen et al used a lot in the literature.  Is it because the wavelet approach is expensive/difficult?

One option is for our new `cddp()` function in PyKE to take a `method="name"` argument that lets you choose between the different flavors of cdpp, but then again we should only really offer the flavors that make actual sense!

**Comment by barentsen** [comment]
This has been added by #160!
